version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          comand: |
            pip3 install --upgrade pip
            pip3 install --user --upgrade tensorflow
      - python/save-cache
      - run:
          command: python manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
